name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, runner-staging-vergolaperth]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          set -e
          echo "Current directory: $(pwd)"
          echo "Listing current directory contents:"
          ls -la

          DEPLOY_PATH="C:/xampp/htdocs/VergolaPerth"
          
          echo "Checking path"
          if [ ! -d "$DEPLOY_PATH" ]; then
            echo "Path does not exist: $DEPLOY_PATH"
            exit 1
          fi

          cd "$DEPLOY_PATH"
    
          echo "Pulling latest updates"
          git pull origin main
    
          echo "Deployment steps completed successfully"
