name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, runner-staging-vergolaperth]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          set -e
          echo "Current directory: $(pwd)"
          echo "Listing current directory contents:"
          ls -la

          cd C:\xampp\htdocs\VergolaPerth
          
          echo "Checking path"
          if [ ! -d "C:\xampp\htdocs\VergolaPerth" ]; then
            echo "Path does not exist: C:\xampp\htdocs\VergolaPerth"
            exit 1
          fi
    
          echo "Pulling latest updates"
          git pull origin main
    
          echo "Deployment steps completed successfully"
